services:
  otel-agent:
    image: otel/opentelemetry-collector-contrib:0.146.0
    hostname: '{{.Node.Hostname}}'
    command: ['--config=https://raw.githubusercontent.com/josemoura212/signoz-observability/main/agent-app/otel-agent-config.yaml']
    network_mode: host
    volumes:
      - /:/hostfs:ro
    environment:
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_ETC: /hostfs/etc
      HOST_VAR: /hostfs/var
      SIGNOZ_ENDPOINT: ${SIGNOZ_ENDPOINT}
    pid: host
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
    logging:
      options:
        max-size: '20m'
        max-file: '3'
