receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  filelog/docker:
    include:
      - /hostfs/var/lib/docker/containers/*/*-json.log
    include_file_path: true
    start_at: end
    operators:
      - type: json_parser
        id: docker_json
      - type: move
        from: attributes.log
        to: body
      - type: move
        from: attributes.stream
        to: attributes["log.iostream"]
      - type: remove
        field: attributes.time

  hostmetrics:
    root_path: /hostfs
    collection_interval: 60s
    scrapers:
      cpu: {}
      load: {}
      memory: {}
      disk: {}
      filesystem: {}
      network: {}
      paging: {}
      process:
        mute_process_name_error: true
        mute_process_exe_error: true
        mute_process_io_error: true
      processes: {}

processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 512
    spike_limit_mib: 128

  batch:
    send_batch_size: 1000
    timeout: 10s

  resourcedetection:
    detectors: [env, system]
    system:
      hostname_sources: ['os']

exporters:
  otlp_grpc:
    endpoint: ${env:SIGNOZ_ENDPOINT}:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [otlp_grpc]

    metrics:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [otlp_grpc]

    logs:
      receivers: [otlp, filelog/docker]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [otlp_grpc]
