services:
  otel-agent:
    image: otel/opentelemetry-collector-contrib:0.146.0
    container_name: otel-agent-mongo
    hostname: ${HOST_NAME}
    restart: unless-stopped
    command: ['--config=https://raw.githubusercontent.com/josemoura212/signoz-observability/main/agent-mongo/otel-agent-config.yaml']
    volumes:
      - /:/hostfs:ro
      - ${MONGO_LOG_PATH:-/var/log/mongodb}:/var/log/mongodb:ro
    network_mode: host
    environment:
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_ETC: /hostfs/etc
      HOST_VAR: /hostfs/var
      SIGNOZ_ENDPOINT: ${SIGNOZ_ENDPOINT}
      MONGO_ENDPOINT: ${MONGO_ENDPOINT:-localhost:27017}
      MONGO_USER: ${MONGO_MONITOR_USER}
      MONGO_PASSWORD: ${MONGO_MONITOR_PASSWORD}
    pid: host
    logging:
      options:
        max-size: '20m'
        max-file: '3'
