services:
  otel-agent:
    image: otel/opentelemetry-collector-contrib:0.146.0
    hostname: ${HOST_NAME}
    command: ['--config=https://raw.githubusercontent.com/josemoura212/signoz-observability/main/agent-app-kafka/otel-agent-config.yaml']
    volumes:
      - /:/hostfs:ro
      - /etc/passwd:/etc/passwd:ro
    environment:
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_ETC: /hostfs/etc
      HOST_VAR: /hostfs/var
      SIGNOZ_ENDPOINT: ${SIGNOZ_ENDPOINT}
      KAFKA_BROKERS: ${KAFKA_BROKERS:-localhost:9092}
    user: "0:0"
    pid: host
    networks:
      - hostnet
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    logging:
      options:
        max-size: '20m'
        max-file: '3'

networks:
  hostnet:
    external: true
    name: host
